### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by clementlrd** [clementlrd/Ray-Tracer#13]
- [x] orientable : utiliser un vecteur normal 
- [x] pivoter l'écran pas uniquement autour de la verticale
- [x] Utiliser la distance focale !
- [x] focus blur ?

**Comment by toniodo** [comment]
In last commits about camera, seems orientable but in reality no

**Comment by clementlrd** [comment]
Focal length is unused ?

**Comment by clementlrd** [comment]
tout marchait bien finalement, juste pour le cas extrême où quand on regarde vers le haut on le bas c'est tout noir, c'est à cause de la manière dont été fait la normalisation pour la couleur du ciel

**Comment by toniodo** [comment]
> @toniodo Focal length is unused ?

Done in commit 1c6335ae1d26de2b07970404ef54a3dd95d7405c
