### ISSUE TITLE
[Material] Fix Dielectric

### ISSUE THREAD

**Issue by clementlrd** [clementlrd/Ray-Tracer#15]

**Comment by toniodo** [comment]
Problem with refraction when the index outside the object is lower than the object

**Comment by clementlrd** [comment]
The rendering does not correspond to reality:
- black circles
- sphere center in not reversed

**Comment by toniodo** [comment]
Implementation of Schlick approximation in commit 80fcd79a0777d3c220a89dff7207209569536de3 , but black circles remains.
